package com.tencent.mm.storage.a;

import com.tencent.mm.e.b.ai;
import com.tencent.mm.protocal.c.ol;
import com.tencent.mmdb.FileUtils;
import java.lang.reflect.Field;

public final class a extends ai {
    public static int TYPE_CUSTOM = 3;
    public static int TYPE_SYSTEM = 1;
    protected static com.tencent.mm.sdk.h.c.a chq;
    public static int nwG = 2;
    public static int nwH = 4;
    public static int nwI = FileUtils.S_IRUSR;
    public static int nwJ = 17;
    public static int nwK = 18;
    public static int nwL = 81;
    public static int nwM = 65;

    static {
        com.tencent.mm.sdk.h.c.a aVar = new com.tencent.mm.sdk.h.c.a();
        aVar.ddU = new Field[29];
        aVar.bXK = new String[30];
        StringBuilder stringBuilder = new StringBuilder();
        aVar.bXK[0] = "productID";
        aVar.nmd.put("productID", "TEXT PRIMARY KEY  COLLATE NOCASE ");
        stringBuilder.append(" productID TEXT PRIMARY KEY  COLLATE NOCASE ");
        stringBuilder.append(", ");
        aVar.nmc = "productID";
        aVar.bXK[1] = "packIconUrl";
        aVar.nmd.put("packIconUrl", "TEXT");
        stringBuilder.append(" packIconUrl TEXT");
        stringBuilder.append(", ");
        aVar.bXK[2] = "packGrayIconUrl";
        aVar.nmd.put("packGrayIconUrl", "TEXT");
        stringBuilder.append(" packGrayIconUrl TEXT");
        stringBuilder.append(", ");
        aVar.bXK[3] = "packCoverUrl";
        aVar.nmd.put("packCoverUrl", "TEXT");
        stringBuilder.append(" packCoverUrl TEXT");
        stringBuilder.append(", ");
        aVar.bXK[4] = "packName";
        aVar.nmd.put("packName", "TEXT");
        stringBuilder.append(" packName TEXT");
        stringBuilder.append(", ");
        aVar.bXK[5] = "packDesc";
        aVar.nmd.put("packDesc", "TEXT");
        stringBuilder.append(" packDesc TEXT");
        stringBuilder.append(", ");
        aVar.bXK[6] = "packAuthInfo";
        aVar.nmd.put("packAuthInfo", "TEXT");
        stringBuilder.append(" packAuthInfo TEXT");
        stringBuilder.append(", ");
        aVar.bXK[7] = "packPrice";
        aVar.nmd.put("packPrice", "TEXT");
        stringBuilder.append(" packPrice TEXT");
        stringBuilder.append(", ");
        aVar.bXK[8] = "packType";
        aVar.nmd.put("packType", "INTEGER");
        stringBuilder.append(" packType INTEGER");
        stringBuilder.append(", ");
        aVar.bXK[9] = "packFlag";
        aVar.nmd.put("packFlag", "INTEGER");
        stringBuilder.append(" packFlag INTEGER");
        stringBuilder.append(", ");
        aVar.bXK[10] = "packExpire";
        aVar.nmd.put("packExpire", "LONG");
        stringBuilder.append(" packExpire LONG");
        stringBuilder.append(", ");
        aVar.bXK[11] = "packTimeStamp";
        aVar.nmd.put("packTimeStamp", "LONG");
        stringBuilder.append(" packTimeStamp LONG");
        stringBuilder.append(", ");
        aVar.bXK[12] = "packCopyright";
        aVar.nmd.put("packCopyright", "TEXT");
        stringBuilder.append(" packCopyright TEXT");
        stringBuilder.append(", ");
        aVar.bXK[13] = "type";
        aVar.nmd.put("type", "INTEGER");
        stringBuilder.append(" type INTEGER");
        stringBuilder.append(", ");
        aVar.bXK[14] = "status";
        aVar.nmd.put("status", "INTEGER");
        stringBuilder.append(" status INTEGER");
        stringBuilder.append(", ");
        aVar.bXK[15] = "sort";
        aVar.nmd.put("sort", "INTEGER default '1' ");
        stringBuilder.append(" sort INTEGER default '1' ");
        stringBuilder.append(", ");
        aVar.bXK[16] = "lastUseTime";
        aVar.nmd.put("lastUseTime", "LONG");
        stringBuilder.append(" lastUseTime LONG");
        stringBuilder.append(", ");
        aVar.bXK[17] = "packStatus";
        aVar.nmd.put("packStatus", "INTEGER default '0' ");
        stringBuilder.append(" packStatus INTEGER default '0' ");
        stringBuilder.append(", ");
        aVar.bXK[18] = "flag";
        aVar.nmd.put("flag", "INTEGER default '0' ");
        stringBuilder.append(" flag INTEGER default '0' ");
        stringBuilder.append(", ");
        aVar.bXK[19] = "recommand";
        aVar.nmd.put("recommand", "INTEGER default '0' ");
        stringBuilder.append(" recommand INTEGER default '0' ");
        stringBuilder.append(", ");
        aVar.bXK[20] = "sync";
        aVar.nmd.put("sync", "INTEGER default '0' ");
        stringBuilder.append(" sync INTEGER default '0' ");
        stringBuilder.append(", ");
        aVar.bXK[21] = "idx";
        aVar.nmd.put("idx", "INTEGER default '0' ");
        stringBuilder.append(" idx INTEGER default '0' ");
        stringBuilder.append(", ");
        aVar.bXK[22] = "BigIconUrl";
        aVar.nmd.put("BigIconUrl", "TEXT");
        stringBuilder.append(" BigIconUrl TEXT");
        stringBuilder.append(", ");
        aVar.bXK[23] = "MutiLanName";
        aVar.nmd.put("MutiLanName", "TEXT");
        stringBuilder.append(" MutiLanName TEXT");
        stringBuilder.append(", ");
        aVar.bXK[24] = "recommandType";
        aVar.nmd.put("recommandType", "INTEGER default '-1' ");
        stringBuilder.append(" recommandType INTEGER default '-1' ");
        stringBuilder.append(", ");
        aVar.bXK[25] = "lang";
        aVar.nmd.put("lang", "TEXT");
        stringBuilder.append(" lang TEXT");
        stringBuilder.append(", ");
        aVar.bXK[26] = "recommandWord";
        aVar.nmd.put("recommandWord", "TEXT");
        stringBuilder.append(" recommandWord TEXT");
        stringBuilder.append(", ");
        aVar.bXK[27] = "buttonType";
        aVar.nmd.put("buttonType", "INTEGER");
        stringBuilder.append(" buttonType INTEGER");
        stringBuilder.append(", ");
        aVar.bXK[28] = "count";
        aVar.nmd.put("count", "INTEGER");
        stringBuilder.append(" count INTEGER");
        aVar.bXK[29] = "rowid";
        aVar.nme = stringBuilder.toString();
        chq = aVar;
    }

    protected final com.tencent.mm.sdk.h.c.a tl() {
        return chq;
    }

    public final ol bxk() {
        ol olVar = new ol();
        olVar.mdM = this.field_productID;
        olVar.gnp = this.field_packIconUrl;
        olVar.mqd = this.field_packName;
        olVar.mqe = this.field_packDesc;
        olVar.mqf = this.field_packAuthInfo;
        olVar.mqg = this.field_packPrice;
        olVar.mqh = this.field_packType;
        olVar.mqi = this.field_packFlag;
        olVar.mql = this.field_packCoverUrl;
        olVar.mqm = (int) this.field_packExpire;
        olVar.mqn = this.field_packCopyright;
        olVar.mqK = (int) this.field_packTimeStamp;
        olVar.mqo = this.field_packPrice;
        return olVar;
    }

    public final String toString() {
        StringBuilder stringBuilder = new StringBuilder();
        stringBuilder.append("field_productID:").append(this.field_productID).append("\n");
        stringBuilder.append("field_packIconUrl:").append(this.field_packIconUrl).append("\n");
        stringBuilder.append("field_packGrayIconUrl:").append(this.field_packGrayIconUrl).append("\n");
        stringBuilder.append("field_packCoverUrl:").append(this.field_packCoverUrl).append("\n");
        stringBuilder.append("field_packName:").append(this.field_packName).append("\n");
        stringBuilder.append("field_packDesc:").append(this.field_packDesc).append("\n");
        stringBuilder.append("field_packAuthInfo:").append(this.field_packAuthInfo).append("\n");
        stringBuilder.append("field_packPrice:").append(this.field_packPrice).append("\n");
        stringBuilder.append("field_packType:").append(this.field_packType).append("\n");
        stringBuilder.append("field_packFlag:").append(this.field_packFlag).append("\n");
        stringBuilder.append("field_packExpire:").append(this.field_packExpire).append("\n");
        stringBuilder.append("field_packTimeStamp:").append(this.field_packTimeStamp).append("\n");
        stringBuilder.append("field_packCopyright:").append(this.field_packCopyright).append("\n");
        stringBuilder.append("field_type:").append(this.field_type).append("\n");
        stringBuilder.append("field_status:").append(this.field_status).append("\n");
        stringBuilder.append("field_sort:").append(this.field_sort).append("\n");
        stringBuilder.append("field_lastUseTime:").append(this.field_lastUseTime).append("\n");
        stringBuilder.append("field_packStatus:").append(this.field_packStatus).append("\n");
        stringBuilder.append("field_recommand:").append(this.field_recommand).append("\n");
        stringBuilder.append("field_sync:").append(this.field_sync).append("\n");
        stringBuilder.append("field_idx:").append(this.field_idx).append("\n");
        stringBuilder.append("field_BigIconUrl:").append(this.field_BigIconUrl).append("\n");
        stringBuilder.append("field_MutiLanName:").append(this.field_MutiLanName).append("\n");
        stringBuilder.append("field_count:").append(this.field_count).append("\n");
        return stringBuilder.toString();
    }
}
