package com.tencent.mm.plugin.sns.ui;

import com.tencent.mm.plugin.sns.data.d;
import com.tencent.mm.plugin.sns.storage.a;
import com.tencent.mm.plugin.sns.storage.b;
import com.tencent.mm.plugin.sns.storage.k;
import com.tencent.mm.protocal.c.aic;
import com.tencent.mm.protocal.c.awa;
import com.tencent.mm.protocal.c.azr;

public final class av {
    public int aeu;
    public String dFj;
    public String dRA;
    public boolean jEb;
    public String jFt;
    public boolean jWA;
    public String jWB;
    public String jWC;
    public a jWD;
    public b jWE;
    public String jWF;
    public String jWG;
    public String jWH;
    public String jWI;
    public String jWJ;
    public boolean jWK;
    public boolean jWL;
    public boolean jWM;
    public int jWN;
    public boolean jWO;
    public String jWP;
    public boolean jWQ;
    public boolean jWR;
    public boolean jWS;
    public boolean jWT;
    public String jWU;
    public String jWV;
    public boolean jWW;
    public boolean jWX;
    public int jWY;
    public boolean jWZ;
    public d jWr;
    public CharSequence jWs = null;
    public com.tencent.mm.i.a jWt;
    public String jWu;
    public long jWv;
    public String jWw;
    public int jWx;
    public int jWy;
    public int jWz;
    public boolean jXa;
    public String jXb;
    public boolean jXc;
    public boolean jXd;
    public int jXe;
    public double jXf;
    public com.tencent.mm.vending.d.b<com.tencent.mm.vending.j.a> jXg;
    public com.tencent.mm.vending.d.b<com.tencent.mm.vending.j.a> jXh;
    public com.tencent.mm.vending.d.b<com.tencent.mm.vending.j.a> jXi;
    public boolean jXj;
    public String jXk;
    public aic jXl;
    public awa jaB;
    public k jaC;
    public azr jaG;
}
