package com.tencent.mm.svg.a.a;

import android.graphics.Canvas;
import android.graphics.Paint;
import android.graphics.Paint.Cap;
import android.graphics.Paint.Join;
import android.graphics.Paint.Style;
import android.graphics.Path;
import android.os.Looper;
import com.tencent.mm.svg.WeChatSVGRenderC2Java;
import com.tencent.mm.svg.c;
import com.tencent.smtt.sdk.WebView;

public final class ag extends c {
    private final int height = 54;
    private final int width = 54;

    protected final int j(int i, Object... objArr) {
        switch (i) {
            case 0:
                return 54;
            case 1:
                return 54;
            case 2:
                Canvas canvas = (Canvas) objArr[0];
                Looper looper = (Looper) objArr[1];
                c.d(looper);
                c.c(looper);
                Paint g = c.g(looper);
                g.setFlags(385);
                g.setStyle(Style.FILL);
                Paint g2 = c.g(looper);
                g2.setFlags(385);
                g2.setStyle(Style.STROKE);
                g.setColor(WebView.NIGHT_MODE_COLOR);
                g2.setStrokeWidth(1.0f);
                g2.setStrokeCap(Cap.BUTT);
                g2.setStrokeJoin(Join.MITER);
                g2.setStrokeMiter(4.0f);
                g2.setPathEffect(null);
                c.a(g2, looper).setStrokeWidth(1.0f);
                Paint a = c.a(g, looper);
                a.setColor(-9145228);
                canvas.save();
                Paint a2 = c.a(a, looper);
                Path h = c.h(looper);
                h.moveTo(0.0f, 0.0f);
                h.lineTo(17.995556f, 0.0f);
                h.cubicTo(17.995556f, 5.998519f, 18.005554f, 11.997038f, 17.995556f, 17.995556f);
                h.cubicTo(11.997038f, 18.005554f, 5.998519f, 17.995556f, 0.0f, 17.995556f);
                h.lineTo(0.0f, 0.0f);
                h.lineTo(0.0f, 0.0f);
                h.close();
                h.moveTo(6.0f, 6.0f);
                h.lineTo(6.0f, 12.0f);
                h.lineTo(12.0f, 12.0f);
                h.lineTo(12.0f, 6.0f);
                h.lineTo(6.0f, 6.0f);
                h.lineTo(6.0f, 6.0f);
                h.close();
                WeChatSVGRenderC2Java.setFillType(h, 2);
                canvas.drawPath(h, a2);
                canvas.restore();
                canvas.save();
                a2 = c.a(a, looper);
                h = c.h(looper);
                h.moveTo(24.0f, 0.0f);
                h.lineTo(36.0f, 0.0f);
                h.lineTo(36.0f, 6.0f);
                h.lineTo(42.0f, 6.0f);
                h.lineTo(42.0f, 12.0f);
                h.lineTo(30.0f, 12.0f);
                h.lineTo(30.0f, 6.01f);
                h.cubicTo(28.0f, 6.0f, 26.0f, 6.0f, 24.0f, 5.99f);
                h.lineTo(24.0f, 0.0f);
                h.lineTo(24.0f, 0.0f);
                h.close();
                WeChatSVGRenderC2Java.setFillType(h, 2);
                canvas.drawPath(h, a2);
                canvas.restore();
                canvas.save();
                a2 = c.a(a, looper);
                h = c.h(looper);
                h.moveTo(42.0f, 0.0f);
                h.lineTo(54.0f, 0.0f);
                h.lineTo(54.0f, 24.0f);
                h.lineTo(48.01f, 24.0f);
                h.cubicTo(48.0f, 22.0f, 48.0f, 20.0f, 47.99f, 18.0f);
                h.lineTo(42.0f, 18.0f);
                h.lineTo(42.0f, 12.0f);
                h.lineTo(48.0f, 12.0f);
                h.lineTo(48.0f, 6.0f);
                h.lineTo(42.0f, 6.0f);
                h.lineTo(42.0f, 0.0f);
                h.lineTo(42.0f, 0.0f);
                h.close();
                WeChatSVGRenderC2Java.setFillType(h, 2);
                canvas.drawPath(h, a2);
                canvas.restore();
                canvas.save();
                g = c.a(a, looper);
                Path h2 = c.h(looper);
                h2.moveTo(24.0f, 12.0f);
                h2.lineTo(30.0f, 12.0f);
                h2.lineTo(30.0f, 18.0f);
                h2.lineTo(24.0f, 18.0f);
                h2.lineTo(24.0f, 12.0f);
                h2.lineTo(24.0f, 12.0f);
                h2.close();
                WeChatSVGRenderC2Java.setFillType(h2, 2);
                canvas.drawPath(h2, g);
                canvas.restore();
                canvas.save();
                g = c.a(a, looper);
                h2 = c.h(looper);
                h2.moveTo(30.0f, 18.0f);
                h2.lineTo(42.0f, 18.0f);
                h2.lineTo(42.0f, 24.0f);
                h2.lineTo(36.0f, 24.0f);
                h2.lineTo(36.0f, 30.0f);
                h2.lineTo(24.0f, 30.0f);
                h2.lineTo(24.0f, 36.0f);
                h2.lineTo(12.0f, 36.0f);
                h2.lineTo(12.0f, 30.0f);
                h2.lineTo(18.0f, 30.0f);
                h2.lineTo(18.0f, 24.0f);
                h2.lineTo(30.0f, 24.0f);
                h2.lineTo(30.0f, 18.0f);
                h2.lineTo(30.0f, 18.0f);
                h2.close();
                WeChatSVGRenderC2Java.setFillType(h2, 2);
                canvas.drawPath(h2, g);
                canvas.restore();
                canvas.save();
                g = c.a(a, looper);
                h2 = c.h(looper);
                h2.moveTo(0.0f, 24.0f);
                h2.lineTo(12.0f, 24.0f);
                h2.lineTo(12.0f, 30.0f);
                h2.lineTo(6.0f, 30.0f);
                h2.lineTo(6.0f, 36.0f);
                h2.lineTo(0.0f, 36.0f);
                h2.lineTo(0.0f, 24.0f);
                h2.lineTo(0.0f, 24.0f);
                h2.close();
                WeChatSVGRenderC2Java.setFillType(h2, 2);
                canvas.drawPath(h2, g);
                canvas.restore();
                canvas.save();
                g = c.a(a, looper);
                h2 = c.h(looper);
                h2.moveTo(36.0f, 30.0f);
                h2.lineTo(42.0f, 30.0f);
                h2.lineTo(42.0f, 36.0f);
                h2.lineTo(36.0f, 36.0f);
                h2.lineTo(36.0f, 30.0f);
                h2.lineTo(36.0f, 30.0f);
                h2.close();
                WeChatSVGRenderC2Java.setFillType(h2, 2);
                canvas.drawPath(h2, g);
                canvas.restore();
                canvas.save();
                a2 = c.a(a, looper);
                h = c.h(looper);
                h.moveTo(48.0f, 30.0f);
                h.lineTo(54.0f, 30.0f);
                h.lineTo(54.0f, 42.0f);
                h.lineTo(48.0f, 42.0f);
                h.lineTo(48.0f, 48.0f);
                h.lineTo(54.0f, 48.0f);
                h.lineTo(54.0f, 54.0f);
                h.lineTo(42.0f, 54.0f);
                h.lineTo(42.0f, 48.0f);
                h.lineTo(36.0f, 48.0f);
                h.lineTo(36.0f, 42.0f);
                h.lineTo(42.0f, 42.0f);
                h.lineTo(42.0f, 36.0f);
                h.lineTo(47.99f, 36.0f);
                h.cubicTo(48.0f, 34.0f, 48.0f, 32.0f, 48.0f, 30.0f);
                h.lineTo(48.0f, 30.0f);
                h.close();
                WeChatSVGRenderC2Java.setFillType(h, 2);
                canvas.drawPath(h, a2);
                canvas.restore();
                canvas.save();
                g = c.a(a, looper);
                h2 = c.h(looper);
                h2.moveTo(6.0f, 36.0f);
                h2.lineTo(12.0f, 36.0f);
                h2.lineTo(12.0f, 42.0f);
                h2.lineTo(6.0f, 42.0f);
                h2.lineTo(6.0f, 36.0f);
                h2.lineTo(6.0f, 36.0f);
                h2.close();
                WeChatSVGRenderC2Java.setFillType(h2, 2);
                canvas.drawPath(h2, g);
                canvas.restore();
                canvas.save();
                g = c.a(a, looper);
                h2 = c.h(looper);
                h2.moveTo(24.0f, 36.0f);
                h2.lineTo(36.0f, 36.0f);
                h2.lineTo(36.0f, 42.0f);
                h2.lineTo(24.0f, 42.0f);
                h2.lineTo(24.0f, 36.0f);
                h2.lineTo(24.0f, 36.0f);
                h2.close();
                WeChatSVGRenderC2Java.setFillType(h2, 2);
                canvas.drawPath(h2, g);
                canvas.restore();
                canvas.save();
                g = c.a(a, looper);
                h2 = c.h(looper);
                h2.moveTo(0.0f, 42.0f);
                h2.lineTo(6.0f, 42.0f);
                h2.lineTo(6.0f, 48.0f);
                h2.lineTo(18.0f, 48.0f);
                h2.lineTo(18.0f, 54.0f);
                h2.lineTo(0.0f, 54.0f);
                h2.lineTo(0.0f, 42.0f);
                h2.lineTo(0.0f, 42.0f);
                h2.close();
                WeChatSVGRenderC2Java.setFillType(h2, 2);
                canvas.drawPath(h2, g);
                canvas.restore();
                canvas.save();
                g = c.a(a, looper);
                h2 = c.h(looper);
                h2.moveTo(18.0f, 42.0f);
                h2.lineTo(24.0f, 42.0f);
                h2.lineTo(24.0f, 48.0f);
                h2.lineTo(18.0f, 48.0f);
                h2.lineTo(18.0f, 42.0f);
                h2.lineTo(18.0f, 42.0f);
                h2.close();
                WeChatSVGRenderC2Java.setFillType(h2, 2);
                canvas.drawPath(h2, g);
                canvas.restore();
                canvas.save();
                g = c.a(a, looper);
                h2 = c.h(looper);
                h2.moveTo(24.0f, 48.0f);
                h2.lineTo(36.0f, 48.0f);
                h2.lineTo(36.0f, 54.0f);
                h2.lineTo(24.0f, 54.0f);
                h2.lineTo(24.0f, 48.0f);
                h2.lineTo(24.0f, 48.0f);
                h2.close();
                WeChatSVGRenderC2Java.setFillType(h2, 2);
                canvas.drawPath(h2, g);
                canvas.restore();
                c.f(looper);
                break;
        }
        return 0;
    }
}
