package com.tencent.mm.compatible.d;

import com.tencent.mm.sdk.platformtools.v;

public final class j {
    public int cdA = -1;
    public int cdB = -1;
    public int cdC = -1;
    public int cdD = -1;
    public int cdE = -1;
    public int cdF = -1;
    public int cdG = -1;
    public int cdH = -1;
    public int cdI = -1;
    public int cdJ = -1;
    public int cdK = -1;
    public int cdL = -1;
    public int cdM = -1;
    public int cdN = -1;
    public double cdO = -1.0d;
    public int cdP = -1;
    public int cdQ = -1;
    public int cdR = -1;
    public int cdS = -1;
    public String cdT = null;
    public String cdU = null;
    public String cdV = null;
    public String cdW = null;
    public String cdX = null;
    public String cdY = null;
    public String cdZ = null;
    public int cdm = -1;
    public int cdn = -1;
    public int cdo = -1;
    public int cdp = -1;
    public int cdq = -1;
    public int cdr = -1;
    public int cds = -1;
    public int cdt = -1;
    public boolean cdu = false;
    public int cdv = -1;
    public int cdw = -1;
    public int cdx = -1;
    public int cdy = -1;
    public int cdz = -1;
    public String cea = null;
    public String ceb = null;
    public String cec = null;
    public String ced = null;
    public String cee = null;
    public String cef = null;
    public int ceg = -1;
    public int ceh = 2;
    public int cei = 1;
    public int cej = 1;
    public int cek = -1;

    public j() {
        reset();
    }

    public final void reset() {
        this.cdm = -1;
        this.cdn = -1;
        this.cdo = -1;
        this.cdp = -1;
        this.cdq = -1;
        this.cdr = -1;
        this.cdt = -1;
        this.cds = -1;
        this.cdw = -1;
        this.cdx = -1;
        this.cdy = -1;
        this.cdz = -1;
        this.cdu = false;
        this.cdv = -1;
        this.cdA = -1;
        this.cdB = -1;
        this.cdC = -1;
        this.cdD = -1;
        this.cdE = -1;
        this.cdH = -1;
        this.cdG = -1;
        this.cdI = -1;
        this.cdJ = -1;
        this.cdF = -1;
        this.cdI = -1;
        this.cdJ = -1;
        this.cdM = -1;
        this.cdP = -1;
        this.cdQ = -1;
        this.cdR = -1;
        this.cdS = -1;
        this.cdT = null;
        this.cdU = null;
        this.cdV = null;
        this.cdW = null;
        this.cdK = -1;
        this.cdX = null;
        this.cdY = null;
        this.cdZ = null;
        this.cea = null;
        this.ceb = null;
        this.cec = null;
        this.cdL = -1;
        this.ced = null;
        this.cee = null;
        this.cef = null;
        this.ceg = -1;
        this.ceh = 2;
        this.cei = 1;
        this.cej = 1;
        this.cdN = -1;
    }

    public final void dump() {
        v.d("MicroMsg.CommonInfo", "js " + this.cdm);
        v.d("MicroMsg.CommonInfo", "stopBluetoothInBR " + this.cdn);
        v.d("MicroMsg.CommonInfo", "stopBluetoothInBU " + this.cdo);
        v.d("MicroMsg.CommonInfo", "setBluetoothScoOn " + this.cdq);
        v.d("MicroMsg.CommonInfo", "startBluetoothSco " + this.cdp);
        v.d("MicroMsg.CommonInfo", "voiceSearchFastMode " + this.cdr);
        v.d("MicroMsg.CommonInfo", "pcmReadMode " + this.cdt);
        v.d("MicroMsg.CommonInfo", "pcmBufferRate " + this.cds);
        v.d("MicroMsg.CommonInfo", "audioPrePro " + this.cdw);
        v.d("MicroMsg.CommonInfo", "voicemsgfd " + this.cdx);
        v.d("MicroMsg.CommonInfo", "htcvoicemode " + this.cdy);
        v.d("MicroMsg.CommonInfo", "samsungvoicemode " + this.cdz);
        v.d("MicroMsg.CommonInfo", "speexBufferRate " + this.cdA);
        v.d("MicroMsg.CommonInfo", "linespe " + this.cdB);
        v.d("MicroMsg.CommonInfo", "fixspan " + this.cdM);
        v.d("MicroMsg.CommonInfo", "extvideo " + this.cdC);
        v.d("MicroMsg.CommonInfo", "extvideosam " + this.cdD);
        v.d("MicroMsg.CommonInfo", "sysvideodegree " + this.cdE);
        v.d("MicroMsg.CommonInfo", "mmnotify " + this.cdH);
        v.d("MicroMsg.CommonInfo", "extsharevcard " + this.cdG);
        v.d("MicroMsg.CommonInfo", "audioformat " + this.cdI);
        v.d("MicroMsg.CommonInfo", "qrcam " + this.cdJ);
        v.d("MicroMsg.CommonInfo", "mBase " + this.cdT);
        v.d("MicroMsg.CommonInfo", "mPackageInfo " + this.cdU);
        v.d("MicroMsg.CommonInfo", "mClassLoader " + this.cdV);
        v.d("MicroMsg.CommonInfo", "mResources " + this.cdW);
        v.d("MicroMsg.CommonInfo", "sysvideofp " + this.cdK);
        v.d("MicroMsg.CommonInfo", "extstoragedir " + this.cdX);
        v.d("MicroMsg.CommonInfo", "extpubdir " + this.cdY);
        v.d("MicroMsg.CommonInfo", "extdatadir " + this.cdZ);
        v.d("MicroMsg.CommonInfo", "extrootdir " + this.cea);
        v.d("MicroMsg.CommonInfo", "extstoragestate " + this.ceb);
        v.d("MicroMsg.CommonInfo", "extcachedir " + this.cec);
        v.d("MicroMsg.CommonInfo", "extvideoplayer " + this.cdL);
        v.d("MicroMsg.CommonInfo", "loadDrawable " + this.ced);
        v.d("MicroMsg.CommonInfo", "loadXmlResourceParser " + this.cee);
        v.d("MicroMsg.CommonInfo", "voipAudioPrePro " + this.cdP);
        v.d("MicroMsg.CommonInfo", "voipAudioPreProNS " + this.cdQ);
        v.d("MicroMsg.CommonInfo", "voipAudioPreProAEC " + this.cdR);
        v.d("MicroMsg.CommonInfo", "voipAudioPreProAGC " + this.cdS);
        v.d("MicroMsg.CommonInfo", "sight full screen type " + this.cef);
        v.d("MicroMsg.CommonInfo", "checkSightDraftMd5 " + this.ceh);
        v.d("MicroMsg.CommonInfo", "swipeBackConfig " + this.cei);
        v.d("MicroMsg.CommonInfo", "qrCodeZoom " + this.cdN);
    }
}
